"""Embedding-based input canonicalization for the composition engine.

The planner emits free-text-ish values (``occasion_signal``,
``weather_context``, etc.) that don't always match the YAML's canonical
keys. Without canonicalization, every realistic turn lands on a
``yaml_gap`` and falls through to the LLM — defeating the engine's
latency win.

This module bridges the vocabulary gap with pre-computed
``text-embedding-3-small`` vectors over each axis's YAML keys + notes.
At runtime the router collects every input value that doesn't
exact-match its YAML and embeds them in a single batched call;
nearest-neighbor (cosine ≥ ``threshold``) wins. Below threshold →
return the original value unchanged so the engine still flags it as
a YAML gap (which is now a *genuine* "engine doesn't know" signal,
not a vocabulary mismatch).

Properties:

- **Determinism preserved.** Same input string → same embedding (model
  is deterministic for a fixed `model` + `dimensions`) → same nearest
  neighbor. Cache keys stay stable.
- **Cheap when canonical.** Exact-match path adds 0ms; embedding only
  fires for non-matching inputs. The same string is also cached
  per-process so "casual" gets embedded once.
- **Per-process embedding bank.** Loaded once from
  ``canonical_embeddings.json`` (next to this module). Cold start =
  one file read, no API call.
- **Failure-tolerant.** Embed API failure or timeout → fall back to
  the raw value (engine still produces output, falls through to LLM
  if the value isn't found).
"""
from __future__ import annotations

import json
import logging
import math
from dataclasses import dataclass
from pathlib import Path
from typing import Callable, Mapping, Sequence

from .yaml_loader import StyleGraph


_log = logging.getLogger(__name__)


# Default cosine threshold below which we DON'T pick the nearest
# neighbour. Calibrated empirically on the four worked-example axes —
# 0.5 cleanly separates "casual"→"everyday_casual" (≈0.65) from
# noise like "balcony" (≈0.3 against any occasion). Tunable via
# the ``threshold`` parameter on canonicalize_inputs.
DEFAULT_THRESHOLD = 0.50


# Path to the pre-computed embeddings file shipped alongside this
# module. Generated by ops/scripts/build_canonical_embeddings.py and
# committed as a static artifact — cold starts don't need an API call.
_DEFAULT_EMBEDDINGS_PATH = Path(__file__).resolve().parent / "canonical_embeddings.json"


# Embedding dimension width — kept narrower than text-embedding-3-small's
# 1536 native dim to shrink the artifact to ~400KB (vs ~2.5MB at 1536).
# 256 dims is enough for occasion / weather / archetype semantic
# distinctions; the keys are short and the notes are stylistically
# distinct enough that the lower-dim space still separates cleanly.
EMBEDDING_DIMENSIONS = 256
EMBEDDING_MODEL = "text-embedding-3-small"


# ─────────────────────────────────────────────────────────────────────────
# Dataclasses
# ─────────────────────────────────────────────────────────────────────────


# An EmbedClient is anything that takes a list of strings and returns
# a list of vectors of the same length. Tests pass a Mock; production
# wraps OpenAI's embeddings endpoint at the call site.
EmbedClient = Callable[[Sequence[str]], list[list[float]]]


@dataclass(frozen=True)
class CanonicalEmbeddings:
    """Pre-computed YAML-key embeddings, per axis.

    The four axes correspond to the input fields that need
    canonicalization (per the design discussion that drove this
    module). Keys are the canonical YAML keys; values are the
    embedding vectors. Loaded once from disk; module-cached.
    """

    occasion: Mapping[str, tuple[float, ...]]
    weather: Mapping[str, tuple[float, ...]]
    archetype: Mapping[str, tuple[float, ...]]
    risk_tolerance: Mapping[str, tuple[float, ...]]
    seasonal: Mapping[str, tuple[float, ...]]
    """SubSeason ∪ SeasonalColorGroup keys flattened into one bank.
    Both palette dimensions co-exist as candidates; the engine's
    dual-dimension exact-match runs before this fallback. When this
    fires it returns the YAML key as-is and the engine looks it up
    in whichever palette dimension contains it."""


@dataclass(frozen=True)
class CanonicalizationResult:
    """The output of canonicalize_inputs(). Carries the canonicalized
    values plus a per-axis trail (``what was raw → what was matched``,
    or None when a gap remained). The trail lets the router/orchestrator
    surface the same signal to dashboards as direct YAML gaps."""

    occasion_signal: str
    weather_context: str
    archetype: str | None
    risk_tolerance: str
    seasonal_color_group: str
    embed_calls: int
    """0 when every value exact-matched (no API call), 1 when at least
    one value needed the batched embed lookup."""

    matches: Mapping[str, tuple[str | None, float | None]]
    """{axis: (matched_key_or_None, cosine_score_or_None)} — one entry
    per axis that went through the embedding path. Empty when every
    axis exact-matched."""


# ─────────────────────────────────────────────────────────────────────────
# Loader
# ─────────────────────────────────────────────────────────────────────────


_EMBEDDINGS_CACHE: dict[Path, CanonicalEmbeddings] = {}


def load_canonical_embeddings(
    path: Path | None = None,
) -> CanonicalEmbeddings:
    """Load the pre-computed embeddings file. Module-cached.

    Returns an empty ``CanonicalEmbeddings`` if the file is missing —
    canonicalization then becomes a no-op (engine sees the raw value,
    falls through to LLM if it doesn't match a YAML key). Logged once.
    """
    p = (path or _DEFAULT_EMBEDDINGS_PATH).resolve()
    if p in _EMBEDDINGS_CACHE:
        return _EMBEDDINGS_CACHE[p]
    if not p.exists():
        _log.warning(
            "Canonical embeddings file missing at %s; canonicalization "
            "will be inert until ops/scripts/build_canonical_embeddings.py "
            "regenerates it.",
            p,
        )
        empty = CanonicalEmbeddings(
            occasion={}, weather={}, archetype={},
            risk_tolerance={}, seasonal={},
        )
        _EMBEDDINGS_CACHE[p] = empty
        return empty
    with open(p, "r", encoding="utf-8") as f:
        data = json.load(f)

    def _to_bank(axis: str) -> Mapping[str, tuple[float, ...]]:
        return {
            str(k): tuple(float(x) for x in v)
            for k, v in (data.get(axis) or {}).items()
        }

    out = CanonicalEmbeddings(
        occasion=_to_bank("occasion"),
        weather=_to_bank("weather"),
        archetype=_to_bank("archetype"),
        risk_tolerance=_to_bank("risk_tolerance"),
        seasonal=_to_bank("seasonal"),
    )
    _EMBEDDINGS_CACHE[p] = out
    return out


def clear_embeddings_cache() -> None:
    """Drop the module-level embeddings cache. Tests use this when
    swapping a fixture file."""
    _EMBEDDINGS_CACHE.clear()


# ─────────────────────────────────────────────────────────────────────────
# Cosine helpers
# ─────────────────────────────────────────────────────────────────────────


def _cosine(a: Sequence[float], b: Sequence[float]) -> float:
    if len(a) != len(b) or not a:
        return 0.0
    dot = 0.0
    norm_a = 0.0
    norm_b = 0.0
    for x, y in zip(a, b):
        dot += x * y
        norm_a += x * x
        norm_b += y * y
    if norm_a == 0.0 or norm_b == 0.0:
        return 0.0
    return dot / (math.sqrt(norm_a) * math.sqrt(norm_b))


def _nearest(
    query: Sequence[float],
    bank: Mapping[str, Sequence[float]],
) -> tuple[str | None, float]:
    """Find the highest-cosine neighbour in the bank. Returns
    (key, score) or (None, 0.0) on an empty bank."""
    best_key: str | None = None
    best_score = -1.0
    for key, vec in bank.items():
        score = _cosine(query, vec)
        if score > best_score:
            best_score = score
            best_key = key
    if best_key is None:
        return None, 0.0
    return best_key, best_score


# ─────────────────────────────────────────────────────────────────────────
# Public API
# ─────────────────────────────────────────────────────────────────────────


def _exact_match_seasonal(value: str, graph: StyleGraph) -> str | None:
    """Spec-special: seasonal_color_group can be either a 12-entry
    SubSeason key or a 4-entry SeasonalColorGroup key. Either matches."""
    if not value:
        return None
    if value in (graph.palette.get("SubSeason") or {}):
        return value
    if value in (graph.palette.get("SeasonalColorGroup") or {}):
        return value
    return None


def canonicalize_inputs(
    inputs,  # CompositionInputs — circular-import safe via duck typing
    *,
    graph: StyleGraph,
    embeddings: CanonicalEmbeddings,
    embed_client: EmbedClient | None,
    threshold: float = DEFAULT_THRESHOLD,
):
    """Return a new CompositionInputs with values canonicalized against
    the YAML key vocabulary.

    Algorithm:
    1. For each canonicalized axis, exact-match against the relevant
       YAML keys. Exact matches keep their value (no API call).
    2. Collect remaining values into a single batched embed call.
    3. For each batched value, nearest-neighbour against its axis's
       pre-computed bank. If cosine ≥ threshold, replace the input
       value with the matched YAML key. Below threshold, leave the
       raw value (engine flags it as YAML gap, router falls through
       to LLM).
    4. On embed-API failure or empty bank, leave the raw value.

    Pure-ish: the only side effect is the batched embed call, which is
    injected via ``embed_client``. Tests pass a Mock that returns
    deterministic vectors.
    """
    from .engine import CompositionInputs  # local import to avoid cycle

    raw_occasion = inputs.occasion_signal
    raw_weather = inputs.weather_context
    raw_archetype = inputs.archetype
    raw_risk = inputs.risk_tolerance
    raw_seasonal = inputs.seasonal_color_group

    # --- Exact-match phase (no API call) ---------------------------------
    exact_occasion = (
        raw_occasion if raw_occasion in graph.occasion else None
    )
    exact_weather = (
        raw_weather if raw_weather in graph.weather else None
    )
    archetype_dim = graph.archetype.get("primary_archetype") or {}
    exact_archetype = (
        raw_archetype if raw_archetype and raw_archetype in archetype_dim else None
    )
    risk_dim = graph.archetype.get("risk_tolerance") or {}
    exact_risk = raw_risk if raw_risk in risk_dim else None
    exact_seasonal = _exact_match_seasonal(raw_seasonal, graph)

    # --- Collect non-matching values for the batched embed call ----------
    pending: list[tuple[str, str, Mapping[str, Sequence[float]]]] = []
    if exact_occasion is None and raw_occasion:
        pending.append(("occasion", raw_occasion, embeddings.occasion))
    if exact_weather is None and raw_weather:
        pending.append(("weather", raw_weather, embeddings.weather))
    if exact_archetype is None and raw_archetype:
        # Archetype is optional — only canonicalize if it was set.
        pending.append(("archetype", raw_archetype, embeddings.archetype))
    if exact_risk is None and raw_risk:
        pending.append(("risk_tolerance", raw_risk, embeddings.risk_tolerance))
    if exact_seasonal is None and raw_seasonal:
        pending.append(("seasonal", raw_seasonal, embeddings.seasonal))

    matches: dict[str, tuple[str | None, float | None]] = {}
    embed_calls = 0

    if pending and embed_client is not None:
        texts = [v for _, v, _ in pending]
        # Count the attempt regardless of outcome so telemetry can
        # distinguish "embed succeeded but no match cleared threshold"
        # from "embed wasn't tried" (e.g. all values exact-matched).
        embed_calls = 1
        try:
            vectors = embed_client(texts)
        except Exception as exc:  # noqa: BLE001 — never break a turn
            _log.warning(
                "canonicalize embed call failed (%d values): %s",
                len(texts), exc,
            )
            vectors = []

        if len(vectors) == len(texts):
            for (axis, _raw, bank), vec in zip(pending, vectors):
                if not bank:
                    matches[axis] = (None, None)
                    continue
                nearest, score = _nearest(vec, bank)
                if nearest is not None and score >= threshold:
                    matches[axis] = (nearest, score)
                else:
                    matches[axis] = (None, score)

    # --- Apply canonicalized values ---------------------------------------
    def _resolve(axis: str, exact: str | None, raw: str) -> str:
        if exact is not None:
            return exact
        if axis in matches and matches[axis][0] is not None:
            return matches[axis][0]  # type: ignore[return-value]
        return raw

    new_occasion = _resolve("occasion", exact_occasion, raw_occasion)
    new_weather = _resolve("weather", exact_weather, raw_weather)
    new_risk = _resolve("risk_tolerance", exact_risk, raw_risk)
    new_seasonal = _resolve("seasonal", exact_seasonal, raw_seasonal)

    # archetype is special: when raw is None or empty, keep it None
    # rather than substituting a canonicalized value (which would
    # promote a non-archetype free-text into an archetype).
    if exact_archetype is not None:
        new_archetype: str | None = exact_archetype
    elif raw_archetype and "archetype" in matches and matches["archetype"][0] is not None:
        new_archetype = matches["archetype"][0]
    else:
        new_archetype = raw_archetype  # may be None

    return (
        CompositionInputs(
            gender=inputs.gender,
            body_shape=inputs.body_shape,
            frame_structure=inputs.frame_structure,
            seasonal_color_group=new_seasonal,
            archetype=new_archetype,
            risk_tolerance=new_risk,
            occasion_signal=new_occasion,
            formality_hint=inputs.formality_hint,
            weather_context=new_weather,
            time_of_day=inputs.time_of_day,
            style_goal=inputs.style_goal,
            direction_id=inputs.direction_id,
            direction_label=inputs.direction_label,
            intent=inputs.intent,
        ),
        CanonicalizationResult(
            occasion_signal=new_occasion,
            weather_context=new_weather,
            archetype=new_archetype,
            risk_tolerance=new_risk,
            seasonal_color_group=new_seasonal,
            embed_calls=embed_calls,
            matches=dict(matches),
        ),
    )


# ─────────────────────────────────────────────────────────────────────────
# Default OpenAI-backed embed client (lazy-init)
# ─────────────────────────────────────────────────────────────────────────


_DEFAULT_CLIENT_HOLDER: dict[str, EmbedClient] = {}


def default_embed_client() -> EmbedClient:
    """Lazy-init OpenAI embed client wrapped as an EmbedClient callable.
    Reuses the catalog retrieval pattern (text-embedding-3-small at
    EMBEDDING_DIMENSIONS).

    Module-singleton so the OpenAI client cost is paid once per process.
    """
    if "client" in _DEFAULT_CLIENT_HOLDER:
        return _DEFAULT_CLIENT_HOLDER["client"]

    from openai import OpenAI
    from user_profiler.config import get_api_key

    raw = OpenAI(api_key=get_api_key())

    def _embed(texts: Sequence[str]) -> list[list[float]]:
        if not texts:
            return []
        response = raw.embeddings.create(
            model=EMBEDDING_MODEL,
            input=list(texts),
            dimensions=EMBEDDING_DIMENSIONS,
        )
        return [list(item.embedding) for item in response.data]

    _DEFAULT_CLIENT_HOLDER["client"] = _embed
    return _embed
