create table if not exists public.catalog_enriched (
  id uuid primary key default gen_random_uuid(),
  upload_id uuid null,
  source_row_number integer null,

  product_id text not null,
  title text null,
  description text null,
  price numeric null,
  images_0_src text null,
  images_1_src text null,
  url text null,

  "GarmentCategory" text null,
  "GarmentSubtype" text null,
  "GarmentLength" text null,
  "SilhouetteContour" text null,
  "SilhouetteType" text null,
  "VolumeProfile" text null,
  "FitEase" text null,
  "FitType" text null,
  "ShoulderStructure" text null,
  "NecklineType" text null,
  "NecklineDepth" text null,
  "SleeveLength" text null,
  "SkinExposureLevel" text null,
  "WaistDefinition" text null,
  "HipDefinition" text null,
  "FabricDrape" text null,
  "FabricWeight" text null,
  "FabricTexture" text null,
  "StretchLevel" text null,
  "EdgeSharpness" text null,
  "ConstructionDetail" text null,
  "EmbellishmentLevel" text null,
  "EmbellishmentType" text null,
  "EmbellishmentZone" text null,
  "VerticalWeightBias" text null,
  "VisualWeightPlacement" text null,
  "StructuralFocus" text null,
  "BodyFocusZone" text null,
  "LineDirection" text null,
  "PatternType" text null,
  "PatternScale" text null,
  "PatternOrientation" text null,
  "ContrastLevel" text null,
  "ColorTemperature" text null,
  "ColorSaturation" text null,
  "ColorValue" text null,
  "ColorCount" text null,
  "FormalitySignalStrength" text null,
  "FormalityLevel" text null,
  "OccasionFit" text null,
  "OccasionSignal" text null,
  "TimeOfDay" text null,
  "GenderExpression" text null,
  "StylingCompleteness" text null,
  "PrimaryColor" text null,
  "SecondaryColor" text null,

  "GarmentCategory_confidence" double precision null,
  "GarmentSubtype_confidence" double precision null,
  "GarmentLength_confidence" double precision null,
  "SilhouetteContour_confidence" double precision null,
  "SilhouetteType_confidence" double precision null,
  "VolumeProfile_confidence" double precision null,
  "FitEase_confidence" double precision null,
  "FitType_confidence" double precision null,
  "ShoulderStructure_confidence" double precision null,
  "NecklineType_confidence" double precision null,
  "NecklineDepth_confidence" double precision null,
  "SleeveLength_confidence" double precision null,
  "SkinExposureLevel_confidence" double precision null,
  "WaistDefinition_confidence" double precision null,
  "HipDefinition_confidence" double precision null,
  "FabricDrape_confidence" double precision null,
  "FabricWeight_confidence" double precision null,
  "FabricTexture_confidence" double precision null,
  "StretchLevel_confidence" double precision null,
  "EdgeSharpness_confidence" double precision null,
  "ConstructionDetail_confidence" double precision null,
  "EmbellishmentLevel_confidence" double precision null,
  "EmbellishmentType_confidence" double precision null,
  "EmbellishmentZone_confidence" double precision null,
  "VerticalWeightBias_confidence" double precision null,
  "VisualWeightPlacement_confidence" double precision null,
  "StructuralFocus_confidence" double precision null,
  "BodyFocusZone_confidence" double precision null,
  "LineDirection_confidence" double precision null,
  "PatternType_confidence" double precision null,
  "PatternScale_confidence" double precision null,
  "PatternOrientation_confidence" double precision null,
  "ContrastLevel_confidence" double precision null,
  "ColorTemperature_confidence" double precision null,
  "ColorSaturation_confidence" double precision null,
  "ColorValue_confidence" double precision null,
  "ColorCount_confidence" double precision null,
  "FormalitySignalStrength_confidence" double precision null,
  "FormalityLevel_confidence" double precision null,
  "OccasionFit_confidence" double precision null,
  "OccasionSignal_confidence" double precision null,
  "TimeOfDay_confidence" double precision null,
  "GenderExpression_confidence" double precision null,
  "StylingCompleteness_confidence" double precision null,
  "PrimaryColor_confidence" double precision null,
  "SecondaryColor_confidence" double precision null,

  row_status text null,
  error_reason text null,
  raw_row_json jsonb not null default '{}'::jsonb,

  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists idx_catalog_enriched_product_id
  on public.catalog_enriched (product_id);

create index if not exists idx_catalog_enriched_upload_id
  on public.catalog_enriched (upload_id);

create index if not exists idx_catalog_enriched_row_status
  on public.catalog_enriched (row_status);

create unique index if not exists uq_catalog_enriched_upload_row
  on public.catalog_enriched (upload_id, source_row_number)
  where upload_id is not null and source_row_number is not null;
