from dataclasses import dataclass
from typing import Any, Dict, Optional

from openai import OpenAI

from user_profiler.config import get_api_key


QUERY_BUILDER_PROMPT = """You generate a structured catalog retrieval query for fashion product search.

Use the provided user context:
- onboarding profile
- user analysis attributes
- deterministic interpretations
- style preference
- immediate need / occasion context

Return a single structured labeled query document that mirrors the catalog embedding document vocabulary.
The output must be concise, retrieval-oriented, and must not mention products by brand or SKU.
Prefer explicit values already present in the provided context. Do not invent unsupported details.

Return only plain text in this exact section structure:

USER_NEED:
- request_summary: ...
- styling_goal: ...

PROFILE_AND_STYLE:
- gender_expression_target: ...
- style_archetype_primary: ...
- style_archetype_secondary: ...
- seasonal_color_group: ...
- contrast_level: ...
- frame_structure: ...
- height_category: ...
- waist_size_band: ...

GARMENT_REQUIREMENTS:
- GarmentCategory: ...
- GarmentSubtype: ...
- StylingCompleteness: complete
- SilhouetteContour: ...
- SilhouetteType: ...
- VolumeProfile: ...
- FitEase: ...
- FitType: ...
- GarmentLength: ...
- ShoulderStructure: ...
- WaistDefinition: ...
- HipDefinition: ...
- NecklineType: ...
- NecklineDepth: ...
- SleeveLength: ...
- SkinExposureLevel: ...

FABRIC_AND_BUILD:
- FabricDrape: ...
- FabricWeight: ...
- FabricTexture: ...
- StretchLevel: ...
- EdgeSharpness: ...
- ConstructionDetail: ...

PATTERN_AND_COLOR:
- PatternType: ...
- PatternScale: ...
- PatternOrientation: ...
- ContrastLevel: ...
- ColorTemperature: ...
- ColorSaturation: ...
- ColorValue: ...
- ColorCount: ...
- PrimaryColor: ...
- SecondaryColor: ...

OCCASION_AND_SIGNAL:
- FormalitySignalStrength: ...
- FormalityLevel: ...
- OccasionFit: ...
- OccasionSignal: ...
- TimeOfDay: ...
"""


@dataclass(frozen=True)
class RetrievalQueryInput:
    profile: Dict[str, Any]
    analysis_attributes: Dict[str, Any]
    derived_interpretations: Dict[str, Any]
    style_preference: Dict[str, Any]
    user_need: str
    user_context: Dict[str, Any]


class StyleRequirementQueryBuilder:
    def __init__(self, model: str = "gpt-5-mini") -> None:
        self._client = OpenAI(api_key=get_api_key())
        self._model = model

    def build_query_document(self, payload: RetrievalQueryInput) -> str:
        response = self._client.responses.create(
            model=self._model,
            input=[
                {"role": "system", "content": [{"type": "input_text", "text": QUERY_BUILDER_PROMPT}]},
                {
                    "role": "user",
                    "content": [
                        {
                            "type": "input_text",
                            "text": str(
                                {
                                    "profile": payload.profile,
                                    "analysis_attributes": payload.analysis_attributes,
                                    "derived_interpretations": payload.derived_interpretations,
                                    "style_preference": payload.style_preference,
                                    "user_need": payload.user_need,
                                    "user_context": payload.user_context,
                                }
                            ),
                        }
                    ],
                },
            ],
        )
        text = getattr(response, "output_text", "") or ""
        if not text.strip():
            raise ValueError("No retrieval query document returned.")
        return text.strip()
